FROM source44/ubuntu:14.04-curl
MAINTAINER Kevin McBride <kmcbride@sourceintelligence.com>

RUN apt-get update && apt-get install -y \
  python-software-properties \
  software-properties-common \
  && rm -rf /var/lib/apt/lists/*
